### ISSUE TITLE
v 1 kinect not working on with mac os 11.3.1 as a webcam

### ISSUE THREAD

**Issue by jazzy7834** [shiffman/OpenKinect-for-Processing#164]
<img width="694" alt="Screenshot 2021-05-25 at 10 03 31 PM" src="https://user-images.githubusercontent.com/84799889/119534973-23a1ec80-bda5-11eb-9b18-72a5f90ac00b.png">
<img width="694" alt="Screenshot 2021-05-25 at 10 03 25 PM" src="https://user-images.githubusercontent.com/84799889/119534980-26044680-bda5-11eb-946c-078e5ff914ab.png">
i want to use my kinect v1 (1414) as a video cam for which ,I have tried everything but nothing is working and the biggest problem is that **initdevice**  is not a function as said by the proccessing program, but whereas iif use the example programs by @shiffman they are working . so If anyone has a solution or any finds any problem in my code then plss lit me know .
